(function () {
  var WRITING_SAMPLES = {
    task1: [
      {
        type: 'Line Graph',
        band: 7,
        prompt: 'The graph below shows the percentage of households in a European country that owned a smartphone, a tablet and a laptop between 2010 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
        sample: 'The line graph illustrates the proportion of households in a European country owning three types of device over a ten-year period from 2010 to 2020.\n\nOverall, ownership of all three devices rose, but smartphones showed the steepest increase and became the most common device by the end of the period. Laptops started highest but grew more slowly, while tablets entered the market later and remained the least widespread.\n\nIn 2010, around 35% of households had a laptop, compared with just 20% for smartphones and almost none for tablets. Over the following five years, smartphone ownership climbed steadily to roughly 60%, overtaking laptops. Tablet ownership appeared around 2012 and reached about 40% by 2015.\n\nBetween 2015 and 2020, smartphone penetration surged to nearly 90%, whereas laptop ownership plateaued at approximately 70%. Tablet ownership continued to grow modestly, finishing at around 55%. The gap between the most and least owned devices widened noticeably after 2015.\n\nIn summary, the decade was defined by the rapid rise of the smartphone, which transformed from a minority device to near-universal adoption, while laptops and tablets grew more gradually.',
        analysis: 'Strengths: clear overview with a key trend, sensible grouping and accurate figures. To reach Band 8: vary sentence structures further and avoid slightly repetitive phrasing such as "ownership".'
      },
      {
        type: 'Bar Chart',
        band: 6,
        prompt: 'The chart below shows the average number of hours per week that men and women in five different age groups spent on housework in 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
        sample: 'The bar chart compares how many hours men and women in five age groups spent doing housework each week in 2020.\n\nIn general, women did more housework than men in every age group. The difference was largest for people aged 30 to 44. Men did the least housework in the 18 to 29 group.\n\nFor women, the 30 to 44 group spent about 16 hours per week, which was the highest. Women aged 45 to 60 spent around 14 hours. Younger women, 18 to 29, did about 10 hours. Older women, over 60, did nearly 12 hours.\n\nFor men, the numbers were lower. Men aged 30 to 44 did about 7 hours, which was still the most for men. The 18 to 29 group did only 4 hours. Men over 60 did about 6 hours. All male groups did less than the female groups.\n\nTo conclude, women spent more time on housework than men, and the busiest period for both was between 30 and 44 years old. The chart shows a clear gap between genders.',
        analysis: 'Strengths: key features selected and basic comparisons made. To reach Band 7: organise by trend rather than listing every figure, and use more precise comparative language.'
      },
      {
        type: 'Pie Chart',
        band: 8,
        prompt: 'The pie charts below show the distribution of household expenditure in a country in 1990 and 2020. Summarise the information by selecting and reporting the main features, and make relevant comparisons.',
        sample: 'The two pie charts compare how households in a single country allocated their spending across six categories in 1990 and 2020.\n\nA clear shift is visible in the relative weight of the main categories. Housing dominated both years but grew from 28% to 35% of total expenditure, making it an even more substantial burden by 2020. Conversely, food shrank dramatically, falling from 25% to just 12%, a reflection of lower relative prices and changed consumption patterns.\n\nTransport rose to become the second-largest category at 20%, up from 14%, while leisure more than doubled its share from 6% to 14%. Spending on health remained comparatively stable, edging from 9% to 11%, and education stayed roughly constant at around 8%. The remaining category, other goods, declined slightly from 18% to 15%.\n\nTaken together, the data suggest a society that devoted a decreasing proportion of income to basic sustenance and a rising proportion to mobility, housing and discretionary leisure. This reallocation indicates both greater affluence and the rising cost of essential services such as accommodation. The most striking contrast remains the halving of food’s share against the steady climb of housing.',
        analysis: 'Strengths: confident overview, accurate percentages and a perceptive interpretation of the change. To reach Band 9: tighten cohesion between sentences and integrate the conclusion more seamlessly.'
      },
      {
        type: 'Table',
        band: 7,
        prompt: 'The table below gives information about the number of international students enrolled at three universities in 2015 and 2020, and the percentage change. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
        sample: 'The table provides data on international student enrolments at three universities in 2015 and 2020, together with the percentage change over the period.\n\nOverall, all three universities saw growth in their international intake, but the rate of increase varied considerably. University B experienced the fastest expansion, whereas University A grew most modestly.\n\nIn 2015, University A hosted the largest number of international students at 8,200, followed by University B with 5,400 and University C with 3,100. By 2020, University A had risen to 9,500, an increase of roughly 16%. University B, however, more than doubled its figure to 11,800, representing a 119% jump that made it the largest host by the end of the period.\n\nUniversity C also grew strongly, from 3,100 to 6,000, a 94% rise. The gap between the smallest and largest institutions narrowed as the lower-ranked universities caught up quickly.\n\nIn summary, while every university attracted more international students, the previously smaller institutions grew at a far quicker pace, reshaping the relative standing of the three by 2020.',
        analysis: 'Strengths: clear summary of overall trend and good use of figures to support points. To reach Band 8: add a sharper opening overview and reduce slight repetition of "University".'
      },
      {
        type: 'Map',
        band: 6,
        prompt: 'The maps below show the same town in 1990 and today. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
        sample: 'The maps show how a town changed between 1990 and the present day.\n\nIn 1990, the town was much smaller. There was a river in the north and a forest in the east. The main road went from west to east. There were two schools and a small hospital.\n\nToday, the town is bigger. The forest in the east is smaller because a new housing area was built there. The river is still there, but a bridge was added so people can cross easily. A new supermarket and a large car park were built near the centre.\n\nThe school on the west side is gone, but a bigger school was built in the south. The hospital is still in the same place but it is larger now. A new bus station appeared next to the main road.\n\nIn conclusion, the town has developed a lot. There are more buildings and roads, but some natural areas like the forest became smaller. The changes made the town more modern and convenient for people.',
        analysis: 'Strengths: main changes identified and comparisons made. To reach Band 7: group changes by theme (e.g. transport, housing) and use more advanced location language such as "to the southeast of".'
      },
      {
        type: 'Process',
        band: 8,
        prompt: 'The diagram below shows how recycled paper is manufactured. Summarise the information by selecting and reporting the main features, and describe the stages of the process.',
        sample: 'The diagram outlines the industrial process by which waste paper is recycled into usable paper products.\n\nThe procedure consists of several sequential stages, beginning with the collection and separation of used paper, which is then transported to a treatment facility. Once there, the paper is sorted by type and grade before being washed in a cleaning solution to remove inks, staples and surface dirt.\n\nAfter cleaning, the material is placed in a tank where it is mixed with water and agitated to produce a pulp. This pulp then passes through a flotation tank, in which air bubbles lift away any remaining ink, after which it is beaten and refined to improve fibre quality. The refined pulp is spread onto a conveyor and passed through heated rollers that press and dry it into continuous sheets.\n\nFinally, the dried sheets are cooled, cut to size and rolled for distribution. Throughout the cycle, excess water is filtered and recycled back into the system, making the process relatively efficient.\n\nIn summary, paper recycling is a multi-stage mechanical and chemical process that transforms discarded paper into fresh sheet material through cleaning, pulping, pressing and finishing.',
        analysis: 'Strengths: accurate sequencing with passive voice and clear stage transitions. To reach Band 9: use a wider range of linking devices and more precise technical vocabulary for each stage.'
      }
    ],
    task2: [
      {
        type: 'Opinion',
        band: 6,
        prompt: 'Some people believe that universities should focus on providing academic skills, while others think they should prepare students for employment. To what extent do you agree or disagree?',
        sample: 'Some people think universities should teach academic skills, but others say they should prepare students for jobs. I think both are important, but employment preparation is more useful for most students in today’s difficult job market.\n\nOn the one hand, academic skills are necessary. Students need to learn how to think, read and write clearly. These skills help them in many parts of life and allow them to understand the world. Also, some subjects like science and law need deep knowledge. Without academic training, society cannot progress, and important research would stop.\n\nOn the other hand, many students worry about finding a job after graduation. If universities teach practical skills, students can get work more easily and feel less stress. For example, learning how to use computers, how to speak in public, or how to work in a team is helpful in almost every career. Many companies say graduates are not ready for work, so universities should listen to this complaint and change their courses.\n\nIn my opinion, universities should do both but give more attention to employment. A balance is good because students need knowledge and also need a job. If a student has only theory, they may fail in the real world, but if they have only skills, they cannot grow later.\n\nIn conclusion, I disagree that universities should only teach academic skills. They should also help students get ready for work, because education should improve a person’s future life and give them real opportunities.',
        analysis: 'Strengths: position is clear and both sides addressed. To reach Band 7: develop ideas with more specific examples and use a wider range of linking words and grammar.'
      },
      {
        type: 'Discussion',
        band: 7,
        prompt: 'Some people say that museums should be entertaining, while others believe their main purpose is to educate. Discuss both views and give your own opinion.',
        sample: 'Museums have long been centres of culture, yet opinions differ on whether they should primarily entertain or educate. Both purposes have merit, and I would argue the most effective museums blend the two rather than choosing one.\n\nThose who favour entertainment point out that modern audiences have short attention spans shaped by digital media. If a museum is dull, visitors simply stay away, and its collections gather dust. Interactive displays, reconstructions and guided storytelling can draw in families and young people who might otherwise never engage with history or art. In this sense, entertainment is a gateway that makes education possible, because a visitor must first be interested before they can learn.\n\nConversely, supporters of the educational role stress that museums hold irreplaceable artefacts and expert knowledge. Their core duty, they argue, is to preserve truth and deepen understanding, not merely to amuse. A museum that prioritises spectacle over substance risks misrepresenting the past, diluting complex stories and wasting public funds that could support scholarship.\n\nIn my view, the dichotomy is false. A well-designed museum can captivate and instruct at once; the emotional pull of an exhibition is precisely what helps facts stick in memory. The aim should be edutainment, where enjoyment draws visitors in and scholarship ensures they leave informed rather than merely impressed.\n\nIn conclusion, museums serve society best when they refuse to choose between the two, using engaging methods to deliver genuine learning that lasts beyond the visit.',
        analysis: 'Strengths: balanced treatment of both views and a clear personal stance. To reach Band 8: sharpen topic sentences and use more sophisticated vocabulary to express nuance.'
      },
      {
        type: 'Advantage/Disadvantage',
        band: 8,
        prompt: 'Some countries are investing heavily in high-speed rail networks. What are the advantages and disadvantages of this development?',
        sample: 'The expansion of high-speed rail represents one of the most significant transport investments of recent decades. While it brings clear benefits in connectivity and sustainability, it also carries substantial costs and social risks that deserve scrutiny.\n\nThe principal advantage is environmental and economic. Electric trains emit far less carbon per passenger than planes or cars, directly supporting climate targets at a time when decarbonisation is urgent. They also knit regions together, allowing commuters to live outside expensive capitals and businesses to reach customers faster. Reduced road congestion and fewer flight delays are further dividends. Japan and France demonstrate how such networks can reshape daily life without sacrificing speed or comfort.\n\nHowever, the disadvantages are considerable. Construction is extraordinarily expensive, often requiring decades to recoup, and the funds may divert spending from schools or hospitals. Routes frequently favour wealthy corridors, leaving rural areas behind and occasionally displacing communities through compulsory land purchase. There is also the risk of stranded assets if passenger forecasts prove optimistic, leaving taxpayers to cover the loss.\n\nOn balance, the long-term advantages outweigh the drawbacks, provided projects are planned with rigorous cost-benefit analysis and genuine regional equity. High-speed rail is not a panacea, but as part of a green transport strategy it is a defensible investment in a low-carbon future that connects rather than divides. Crucially, success depends on pairing the tracks with fairer housing and labour policies, so the productivity gains are shared rather than captured by a wealthy few.',
        analysis: 'Strengths: well-balanced advantages and disadvantages with a measured conclusion. To reach Band 9: integrate more precise data and vary sentence openings to avoid a listing feel.'
      },
      {
        type: 'Problem/Solution',
        band: 6,
        prompt: 'Many young people today spend too much time on social media. What problems does this cause, and what solutions can you suggest?',
        sample: 'It is true that many young people spend too much time on social media. This creates some serious problems, and there are practical ways to solve them before the habit becomes worse.\n\nOne problem is health. If young people use phones all day, they do not exercise and their eyes get tired. They may also sleep badly because of bright screens at night. Another problem is study. Students may check messages during homework and lose concentration, so they get bad marks. Also, some young people feel sad or anxious when they compare their life with others online, which hurts their confidence.\n\nA second problem is family relationships. When everyone looks at a screen, they talk less. Parents and children may become distant, and the home feels cold. This is bad for the family and for the child’s development in the long term.\n\nThere are several solutions. First, schools should teach students about the danger of too much screen time and show them how to use it safely. Second, parents can make rules, for example no phones at dinner or after a certain hour. Third, young people can find hobbies like sport or music to use their free time better and meet friends in person.\n\nIn my opinion, the best solution is balance. Phones are useful, but people should control them. If young people learn to use social media for a short time only, the problems will become smaller and life will be healthier.\n\nIn conclusion, too much social media causes health and family problems, but education and good rules can help young people use it in a better way.',
        analysis: 'Strengths: problems and solutions are clearly organised. To reach Band 7: explain causes more deeply and use more advanced vocabulary instead of repeating "problem" and "young people".'
      },
      {
        type: 'Two-part Question',
        band: 7,
        prompt: 'In many cities, the cost of housing has risen sharply. Why is this happening, and what effects does it have on society?',
        sample: 'Soaring housing costs have become a defining anxiety of urban life in many countries. This essay will examine the causes of the trend and its consequences for society.\n\nThe primary driver is a mismatch between supply and demand. Rapid urbanisation concentrates jobs in cities, yet construction lags behind, pushing prices upward. Low interest rates and the treatment of property as an investment by both domestic and foreign buyers further inflates values. Weak regulation of empty homes allows wealthy owners to hold assets without occupancy, tightening the available stock and excluding ordinary residents from the market.\n\nThe effects are wide-ranging. Most directly, essential workers such as nurses and teachers are priced out, forcing long commutes that erode family time and raise pollution. Younger generations delay independence, remaining with parents and postponing marriage or children, which slowly reshapes social structures. Inequality widens as homeowners accumulate wealth while renters fall behind, feeding resentment and reducing social mobility across the population.\n\nIn the longer term, unaffordable cities risk losing their creative and working-class vitality, becoming enclaves for the rich. This undermines the very diversity that makes urban centres dynamic and innovative, and it can fuel political discontent as the gap between owners and renters grows.\n\nIn conclusion, rising housing costs stem from constrained supply and speculative demand, and they impose serious costs on equality, mobility and the social fabric of cities that no single policy can ignore. Governments must therefore act on both sides at once, building more homes while curbing speculative buying, if urban life is to remain open to all.',
        analysis: 'Strengths: both questions answered with logical causes and effects. To reach Band 8: develop the second part with more concrete examples and vary sentence structure.'
      },
      {
        type: 'Opinion',
        band: 8,
        prompt: 'Some people argue that governments should invest in art and music, while others believe this money should be spent on more important priorities. To what extent do you agree or disagree?',
        sample: 'Public funding for the arts is frequently contested on the grounds that it diverts resources from pressing needs. I would argue, however, that supporting art and music is not a luxury but a legitimate public investment with measurable returns that strengthen society as a whole.\n\nThose who oppose such spending have a reasonable case: in societies with inadequate healthcare or education, subsidising galleries can appear indulgent. Taxpayers may resent funding pursuits they do not personally enjoy, and market forces might seem better placed to decide cultural value. This view treats the arts as peripheral to survival and therefore dispensable in hard times.\n\nYet this position is short-sighted. Art and music are not mere decoration; they underpin tourism, mental health and national identity, all of which carry economic weight. Cities with vibrant cultural scenes attract talent and investment, while community arts programmes reduce isolation and crime. Moreover, the arts preserve a society’s memory and critical voice, functions no free market reliably provides. A civilisation that funds only the instrumental impoverishes itself and loses the means to question its own direction.\n\nIn my view, the question is not whether to fund the arts but how much, and with what accountability. A modest, well-targeted commitment — prioritising accessible public culture over elite institutions — yields social cohesion that indirectly strengthens every other sector of public life.\n\nTherefore, I largely disagree with those who would defund the arts, provided the spending is balanced, transparent and reaches ordinary citizens rather than a privileged few.',
        analysis: 'Strengths: nuanced position with counter-argument and clear examples. To reach Band 9: tighten the thesis and use even more precise lexical items to express concession.'
      },
      {
        type: 'Discussion',
        band: 6,
        prompt: 'Some people think children should start school as early as possible, while others believe they should start later. Discuss both views and give your opinion.',
        sample: 'People have different views about when children should start school. Some say early, others say later. Both sides have reasons, and the best answer may depend on the child and the family.\n\nThose who support an early start think children learn faster when they are young. If they go to school at three or four, they can learn language and numbers early, which helps later study. Also, working parents need a safe place for their children during the day, so school or kindergarten is practical. Early school may help poor children who do not have books or quiet space at home.\n\nHowever, other people believe a later start is better. They say young children need time to play and be with family, because play is how small children learn about the world. If children study too early, they may feel stress and lose interest in learning before they even begin. In some countries, children are happier and more confident because they start school at six or seven.\n\nIn my opinion, a middle way is best. Children need play, but they also need some learning with other children. Starting at five years old seems good for most children. Parents and teachers should make school fun, not difficult, so the child is not afraid.\n\nTo conclude, early and late starts both have good points. I think children should begin school at a normal age with kind teachers, so they love learning from the very start.',
        analysis: 'Strengths: both views presented and a personal opinion given. To reach Band 7: extend ideas with examples and use more varied linking and grammar.'
      },
      {
        type: 'Advantage/Disadvantage',
        band: 7,
        prompt: 'More and more people are choosing to live in multigenerational households. What are the advantages and disadvantages of this trend?',
        sample: 'The return of multigenerational living, where grandparents, parents and children share a home, is a notable social shift. It offers real benefits but also creates tensions that should not be ignored by policymakers or families considering it.\n\nThe advantages are chiefly economic and emotional. Pooling incomes eases the burden of rent or mortgages, which is vital in expensive cities where young couples struggle alone. Childcare becomes simpler and cheaper when grandparents are present, and elderly relatives receive daily company that protects them from loneliness and isolation. Culturally, it preserves the transmission of traditions and family stories that nuclear living often loses in busy modern life.\n\nThe disadvantages centre on privacy and conflict. Three generations under one roof can clash over routines, discipline and noise, particularly where space is limited and everyone is under stress. Younger adults may feel watched and infantilised, while elders can resent the loss of independence. Financial strain may simply be shared rather than solved if several members are unemployed at the same time.\n\nOverall, the arrangement suits families with mutual respect and adequate space, but falters without clear boundaries and agreed rules. The practical gains in cost and care are significant, yet they depend on tolerant relationships and a willingness to compromise.\n\nIn conclusion, multigenerational households offer strong support and savings, but risk friction; their success hinges less on the model than on the people within it. With honest communication and enough space, however, the arrangement can enrich every generation and prove more resilient than the isolated nuclear family.',
        analysis: 'Strengths: balanced advantages and disadvantages with a thoughtful conclusion. To reach Band 8: use more sophisticated vocabulary and sharper topic sentences.'
      },
      {
        type: 'Problem/Solution',
        band: 8,
        prompt: 'Traffic congestion in city centres is worsening. What problems does it create, and what measures could authorities take to solve them?',
        sample: 'Urban traffic congestion has evolved from an inconvenience into a structural problem, imposing costs that extend well beyond delayed commuters. This essay identifies the principal problems and evaluates viable policy responses available to authorities.\n\nThe problems are threefold. Economically, lost hours in traffic reduce productivity and raise the cost of moving goods, eroding the competitiveness of city businesses. Environmentally, idling vehicles intensify air pollution and carbon emissions, worsening public health and contributing to climate change. Socially, congestion deepens inequality: the affluent retreat to cars while the poor endure crowded, slow public transport, and road space is monopolised by those who need it least.\n\nEffective solutions require a mix of restriction and investment. Congestion charging, proven in London and Singapore, prices road use and discourages unnecessary trips. Crucially, the revenue should fund expanded, affordable public transport so alternatives become genuinely attractive. Complementary measures include dedicated bus lanes, cycling infrastructure and incentives for remote work, which permanently lowers demand on the network during peak hours.\n\nWithout supply-side improvement, however, charges merely penalise. The coherent approach pairs deterrence with a superior alternative, ensuring behavioural change is practical rather than punitive and accepted by the public.\n\nIn conclusion, congestion damages economy, environment and equity; authorities should combine road pricing with major investment in public transit to deliver lasting relief. Only by treating mobility as a shared public good, rather than a private convenience, can cities remain liveable for the decades ahead. The cost of inaction is simply too high to ignore any longer.',
        analysis: 'Strengths: clear problem categorisation and practical, evaluated solutions. To reach Band 9: integrate more specific evidence and refine the link between problems and measures.'
      },
      {
        type: 'Two-part Question',
        band: 6,
        prompt: 'People today eat more fast food than in the past. Why has this happened, and what effect does it have on people’s health?',
        sample: 'Nowadays people eat more fast food than before. This essay will look at the reasons for this change and the effect it has on people’s health in the modern world.\n\nThere are some clear reasons for this change. First, fast food is quick. Many people work long hours and have no time to cook, so they buy food on the way home. Second, it is cheap, so students and workers can buy it easily without spending much money. Third, advertising on TV and the internet makes fast food popular, especially among children who ask their parents to visit the restaurants. Also, many shops open late, which is convenient for people who finish work at night.\n\nThe effect on health is mostly negative. Fast food has a lot of fat, salt and sugar. If people eat it often, they may become overweight and develop serious conditions. This can cause heart problems and diabetes later in life. Children who eat too much may not grow in a healthy way and can lose energy at school. Some people also feel tired because the food has little real nutrition and too many empty calories.\n\nHowever, not everyone is unhealthy. If a person eats fast food only sometimes and exercises regularly, the risk is smaller. But for many, the habit is daily, and that is the real problem facing public health today.\n\nIn conclusion, fast food is popular because it is fast, cheap and advertised, but eating too much harms health by causing weight gain and heart problems. People should try to cook more at home and treat fast food as an occasional choice.',
        analysis: 'Strengths: both parts answered with relevant reasons and effects. To reach Band 7: develop causes with more depth and use a wider range of health-related vocabulary.'
      }
    ]
  };
  global.WRITING_SAMPLES = WRITING_SAMPLES;
})();
